### ISSUE TITLE
Add more to Feedforward

### ISSUE THREAD

**Issue by nickschatz** [FRC-PDR/ProgrammingDoneRight#55]
The Feedforward section right now addresses only using feedforward to run a velocity loop, and doesn't mention how to use it to control non-linear position systems (heavy arm, elevator affected by gravity, friction), or using it to model systems (position and velocity) where the response can be improved by more modeling (drivetrain.)

I propose writing a paragraph or so about feedforward *as a function* instead of as a constant parameter to be tuned. Included with this should be models for common FRC mechanisms, including the aforementioned heavy arm, elevator, and drivetrain. Maybe have the derivation of these models as well, as well as showing how to determine the parameters of these models. 

Some explanation should be given about why just throwing P,I,D at the system doesn't usually produce an acceptable response.

**Comment by twinters007** [comment]
It's hard for teams to use feedforward as a function since wpilib's PIDController only lets you set a constant parameter (IIRC)

**Comment by nickschatz** [comment]
This article isn't about WPILib's PID controller though... It's not super hard to recalculate the feedforward every iterative loop either though. Unfortunately though the PIDController class kinda does its own thing with the feedforward, plus the integrator on velocity and stuff like that. I don't know if I would recommend using it to anyone, but that's another issue.

**Comment by calcmogul** [comment]
You can override PIDController.calculateFeedforward() to do a custom/non-constant feedforward if you want. For next season, we're intending to make PIDController provide Kv and Ka instead (wpilibsuite/allwpilib#978) in addition to a slew of other currently open PRs against PIDController.

Regarding mechanism model derivations, you might be interested in this paper I've been working on for a while: https://file.tavsys.net/control/state-space-guide.pdf. The models are in the "State-space model examples" section.
